import { DomainNode, SubLawItem, RIConcern, GraphKPIMetrics, CategoryBranch } from './types';

export const CONSTITUTION_NODE = {
  id: 'constitution',
  name: 'Constitution',
  percentage: 47,
  color: '#f59e0b',
  glowColor: 'rgba(245, 158, 11, 0.6)',
  radius: 34,
};

export const DOMAIN_NODES: DomainNode[] = [
  {
    id: 'gov-affairs',
    name: 'Government affairs',
    category: 'Governance',
    percentage: 31,
    color: '#e879f9',
    glowColor: 'rgba(232, 121, 249, 0.5)',
    radius: 24,
    x: -0.42,
    y: -0.65,
    subNodeCount: 39,
    subNodes: [
      { id: 'gov-1', label: 'Legislation', count: 39, color: '#a855f7', angleOffset: -0.2, distance: 45 },
      { id: 'gov-2', label: 'Entities', count: 11, color: '#38bdf8', angleOffset: -0.8, distance: 55 },
      { id: 'gov-3', label: 'Services', count: 35, color: '#34d399', angleOffset: -1.4, distance: 65 },
      { id: 'gov-4', label: 'Procedures', count: 36, color: '#c084fc', angleOffset: 0.6, distance: 48 },
    ],
  },
  {
    id: 'environment',
    name: 'Environment and na...',
    category: 'Environment',
    percentage: 17,
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
    radius: 22,
    x: 0.05,
    y: -0.62,
    subNodeCount: 25,
    subNodes: [
      { id: 'env-1', label: 'Eco Systems', count: 25, color: '#34d399', angleOffset: -0.5, distance: 45 },
      { id: 'env-2', label: 'Directives', count: 18, color: '#fbbf24', angleOffset: 0.3, distance: 50 },
      { id: 'env-3', label: 'Emissions', count: 15, color: '#38bdf8', angleOffset: 0.9, distance: 40 },
    ],
  },
  {
    id: 'sport',
    name: 'Sport',
    category: 'Recreation',
    percentage: 24,
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.5)',
    radius: 20,
    x: 0.38,
    y: -0.78,
    subNodeCount: 18,
    subNodes: [
      { id: 'spo-1', label: 'Federations', count: 18, color: '#fbbf24', angleOffset: -0.4, distance: 40 },
      { id: 'spo-2', label: 'Leagues', count: 34, color: '#34d399', angleOffset: 0.7, distance: 50 },
    ],
  },
  {
    id: 'economy',
    name: 'Economy and Busin...',
    category: 'Economy',
    percentage: 15,
    color: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.5)',
    radius: 24,
    x: 0.65,
    y: -0.45,
    subNodeCount: 24,
    subNodes: [
      { id: 'eco-1', label: 'Finance', count: 19, color: '#34d399', angleOffset: 0.3, distance: 50 },
      { id: 'eco-2', label: 'Trade', count: 24, color: '#38bdf8', angleOffset: 0.7, distance: 60 },
      { id: 'eco-3', label: 'Markets', count: 12, color: '#fbbf24', angleOffset: -0.8, distance: 42 },
    ],
  },
  {
    id: 'security',
    name: 'Security and safety',
    category: 'Security',
    percentage: 23,
    color: '#e879f9',
    glowColor: 'rgba(232, 121, 249, 0.5)',
    radius: 22,
    x: 0.75,
    y: -0.22,
    subNodeCount: 23,
    subNodes: [
      { id: 'sec-1', label: 'Defence', count: 6, color: '#fbbf24', angleOffset: -0.6, distance: 40 },
      { id: 'sec-2', label: 'Cyber', count: 4, color: '#38bdf8', angleOffset: 0.5, distance: 45 },
    ],
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    category: 'Healthcare',
    percentage: 11,
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.6)',
    radius: 22,
    x: 0.45,
    y: -0.02,
    subNodeCount: 42,
    subNodes: [
      { id: 'hea-1', label: 'Medical Laws', count: 18, color: '#fbbf24', angleOffset: 0.2, distance: 45 },
      { id: 'hea-2', label: 'Hospitals', count: 11, color: '#38bdf8', angleOffset: -0.4, distance: 42 },
      { id: 'hea-3', label: 'Insurance', count: 5, color: '#a855f7', angleOffset: -0.9, distance: 38 },
    ],
  },
  {
    id: 'education',
    name: 'Education',
    category: 'Education',
    percentage: 25,
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.5)',
    radius: 23,
    x: 0.65,
    y: 0.18,
    subNodeCount: 30,
    subNodes: [
      { id: 'edu-1', label: 'Schools', count: 12, color: '#34d399', angleOffset: 0.4, distance: 45 },
      { id: 'edu-2', label: 'Universities', count: 8, color: '#fbbf24', angleOffset: -0.3, distance: 40 },
    ],
  },
  {
    id: 'family',
    name: 'Family and commun...',
    category: 'Social Affairs',
    percentage: 33,
    color: '#fbbf24',
    glowColor: 'rgba(251, 191, 36, 0.5)',
    radius: 23,
    x: 0.78,
    y: 0.38,
    subNodeCount: 35,
    subNodes: [
      { id: 'fam-1', label: 'Welfare', count: 35, color: '#38bdf8', angleOffset: -0.4, distance: 45 },
      { id: 'fam-2', label: 'Community', count: 27, color: '#34d399', angleOffset: 0.3, distance: 50 },
      { id: 'fam-3', label: 'Youth', count: 16, color: '#fbbf24', angleOffset: 0.8, distance: 42 },
    ],
  },
  {
    id: 'justice',
    name: 'Justice and Judiciary',
    category: 'Legal',
    percentage: 13,
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
    radius: 24,
    x: -0.1,
    y: 0.55,
    subNodeCount: 36,
    subNodes: [
      { id: 'jus-1', label: 'Courts', count: 36, color: '#fbbf24', angleOffset: -0.3, distance: 45 },
      { id: 'jus-2', label: 'Decrees', count: 29, color: '#c084fc', angleOffset: -0.8, distance: 52 },
      { id: 'jus-3', label: 'Arbitration', count: 13, color: '#34d399', angleOffset: 0.5, distance: 40 },
    ],
  },
  {
    id: 'culture',
    name: 'Culture and media',
    category: 'Culture',
    percentage: 22,
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
    radius: 23,
    x: -0.5,
    y: 0.22,
    subNodeCount: 26,
    subNodes: [
      { id: 'cul-1', label: 'Heritage', count: 26, color: '#38bdf8', angleOffset: 0.5, distance: 45 },
      { id: 'cul-2', label: 'Broadcasting', count: 20, color: '#34d399', angleOffset: -0.6, distance: 42 },
    ],
  },
  {
    id: 'energy',
    name: 'Energy, transport an...',
    category: 'Infrastructure',
    percentage: 38,
    color: '#f472b6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
    radius: 24,
    x: -0.48,
    y: -0.28,
    subNodeCount: 38,
    subNodes: [
      { id: 'ene-1', label: 'Clean Energy', count: 19, color: '#38bdf8', angleOffset: -0.4, distance: 42 },
      { id: 'ene-2', label: 'Logistics', count: 16, color: '#fbbf24', angleOffset: 0.5, distance: 46 },
    ],
  },
];

export const CATEGORY_BRANCHES: CategoryBranch[] = [
  { id: 'services', icon: 'services', label: 'Services', count: 18 },
  { id: 'entities', icon: 'entities', label: 'Entities', count: 3 },
  { id: 'laws', icon: 'laws', label: 'Related Federal Laws', count: 24, isActive: true },
  { id: 'kpis', icon: 'kpis', label: 'KPIs', count: 32 },
  { id: 'regulations', icon: 'regulations', label: 'Related Federal Laws', count: 12 },
];

export const SUB_LAWS_LIST: SubLawItem[] = [
  {
    id: 'law-42',
    title: 'Federal Decree-Law No. (42) of 2022 Promulgating the Civil Procedure Code',
    gaps: 12,
    status: 'negative',
    sentiment: 45,
    servicesCount: 11,
    entitiesCount: 6,
    complaintsCount: 11,
    regulationsCount: 2,
    lastUpdated: '01 Oct 2024',
    category: 'Healthcare',
    description: 'Promulgating the modern judicial procedural framework and digital litigation proceedings across healthcare and institutional entities.',
  },
  {
    id: 'sub-bny-1',
    title: 'Bank of New York Mellon Regulatory Framework (GAPS 25%)',
    gaps: 25,
    status: 'negative',
    sentiment: 38,
    servicesCount: 14,
    entitiesCount: 4,
    complaintsCount: 9,
    regulationsCount: 3,
    lastUpdated: '15 Sep 2024',
    category: 'Finance',
    description: 'Cross-border banking alignment and capital reserve directives for foreign subsidiaries.',
  },
  {
    id: 'sub-mental-health',
    title: 'Federal Law on Mental Health & Patient Welfare',
    gaps: 12,
    status: 'warning',
    sentiment: 52,
    servicesCount: 9,
    entitiesCount: 5,
    complaintsCount: 6,
    regulationsCount: 1,
    lastUpdated: '22 Aug 2024',
    category: 'Healthcare',
    description: 'Comprehensive guidelines establishing psychiatric patient protections, institutional compliance, and clinic standards.',
  },
  {
    id: 'sub-emirates-citigroup',
    title: 'Emirates Citigroup Digital Escrow Regulation',
    gaps: 8,
    status: 'positive',
    sentiment: 68,
    servicesCount: 22,
    entitiesCount: 8,
    complaintsCount: 3,
    regulationsCount: 4,
    lastUpdated: '12 Nov 2024',
    category: 'Banking',
    description: 'Standards for automated clearinghouse escrow accounts and cryptographic verification of assets.',
  },
  {
    id: 'sub-cap-one',
    title: 'Capital One Emirates Consumer Protection Act',
    gaps: 8,
    status: 'positive',
    sentiment: 72,
    servicesCount: 16,
    entitiesCount: 3,
    complaintsCount: 4,
    regulationsCount: 2,
    lastUpdated: '05 Jul 2024',
    category: 'Commerce',
    description: 'Consumer privacy safeguards and automated disclosure of micro-lending fees.',
  },
  {
    id: 'sub-bny-2',
    title: 'Bank of New York Asset Custody Standard (GAPS 16%)',
    gaps: 16,
    status: 'negative',
    sentiment: 41,
    servicesCount: 8,
    entitiesCount: 2,
    complaintsCount: 12,
    regulationsCount: 1,
    lastUpdated: '18 Jun 2024',
    category: 'Finance',
    description: 'Secondary market settlement regulations and fiduciary liability disclosures.',
  },
  {
    id: 'sub-east-west',
    title: 'East West Emirates Maritime Logistics Protocol',
    gaps: 11,
    status: 'warning',
    sentiment: 49,
    servicesCount: 19,
    entitiesCount: 7,
    complaintsCount: 8,
    regulationsCount: 3,
    lastUpdated: '30 May 2024',
    category: 'Maritime',
    description: 'Port customs clearance streamlining and automated vessel manifests.',
  },
  {
    id: 'sub-bny-3',
    title: 'Bank of New York Security Clearinghouses (GAPS 14%)',
    gaps: 14,
    status: 'warning',
    sentiment: 44,
    servicesCount: 10,
    entitiesCount: 3,
    complaintsCount: 7,
    regulationsCount: 2,
    lastUpdated: '14 Apr 2024',
    category: 'Finance',
    description: 'Counterparty default risk mitigations and real-time margin requirements.',
  },
];

export const RI_CONCERNS: RIConcern[] = [
  {
    id: 'concern-1',
    type: 'critical',
    title: 'Critical Concerns',
    lawName: 'Federal Decree-Law No. (42)',
    description: 'The following legislations have faced unexpected challenges from multiple entities throughout the implementation process.',
    targetLawId: 'law-42',
  },
  {
    id: 'concern-2',
    type: 'deregulation',
    title: 'Propose De-regulation',
    lawName: 'Federal Law on Mental Health',
    description: 'Multiple regulations were found to be out of date in the following domains.',
    targetLawId: 'sub-mental-health',
  },
];

export const TIMELINE_YEARS = [2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024];

export const KPI_YEAR_DATA: Record<number, GraphKPIMetrics> = {
  2016: { complianceRate: 18, totalLaws: '42 K', publicEngagement: '28 K', implementationRate: 12 },
  2017: { complianceRate: 22, totalLaws: '48 K', publicEngagement: '34 K', implementationRate: 15 },
  2018: { complianceRate: 27, totalLaws: '55 K', publicEngagement: '45 K', implementationRate: 16 },
  2019: { complianceRate: 31, totalLaws: '60 K', publicEngagement: '52 K', implementationRate: 18 },
  2020: { complianceRate: 35, totalLaws: '65 K', publicEngagement: '60 K', implementationRate: 19 },
  2021: { complianceRate: 58, totalLaws: '92 K', publicEngagement: '84 K', implementationRate: 34 },
  2022: { complianceRate: 74, totalLaws: '124 K', publicEngagement: '118 K', implementationRate: 46 },
  2023: { complianceRate: 89, totalLaws: '148 K', publicEngagement: '142 K', implementationRate: 52 },
  2024: { complianceRate: 98, totalLaws: '165 K', publicEngagement: '165 K', implementationRate: 57 },
};
